name: stockNLP
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.7
  - pip:
    - alpha-vantage==2.3.1
    - altair==4.1.0
    - collection==0.1.6
    - coverage==6.2
    - coveralls==3.3.1
    - datetime==4.3
    - decorator==5.1.0
    - flake8==4.0.1
    - keras==2.7.0
    - matplotlib==3.5.0
    - nltk==3.6.5
    - numpy==1.21.4
    - pandas==1.3.4
    - pep8==1.7.1
    - pip==21.3.1
    - plotly==5.4.0
    - psaw==0.1.0
    - pyflakes==2.4.0
    - pylint==2.12.1
    - pyyaml==6.0
    - requests==2.26.0
    - schedule==1.1.0
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - smmap==5.0.0
    - sonopy==0.1.2
    - streamlit==1.2.0
    - tabulate==0.8.9
    - tensorflow==2.7.0
    - tweepy==4.4.0
    - vader==0.0.3
    - yfinance==0.1.67
prefix: /home/moses/miniconda3/envs/stockNLP
